package com.example.tapiwa.todoapp.fragmentFactory;

public enum FragmentName {
    DAILY_TASKS, WEEKLY_TASKS, MONTHLY_TASKS, YEARLY_TASKS, LONG_TERM_TASKS,
    CUSTOM_PROJECTS, GROUP_PROJECTS, SINGLE_GROUP_PROJECT, CUSTOM_PROJECT, BOTTOM_SHEET_MENU
}

