package com.example.tapiwa.todoapp.FragmentFactory;

public enum FragmentName {
    DAILY_TASKS, WEEKLY_TASKS, MONTHLY_TASKS, YEARLY_TASKS, LONG_TERM_TASKS,
    PERSONAL_PROJECTS, SHARED_PROJECTS, SINGLE_SHARED_PROJECT, PERSONAL_PROJECT, BOTTOM_SHEET_MENU
}

